/**
 * Sprint M19 · Tournament Type Catalog
 * ─────────────────────────────────────
 * 11 tournament types extracted from the MPCA tournament utility (HTML).
 * Used by the two-step Create-Tournament flow — Step 1 shows this catalog,
 * Step 2 collects basic name/season/host/dates and creates the tournament
 * with `tournament_type_code` set for downstream input-variable forms.
 */

export const TOURNAMENT_TYPE_CATALOG = [
    {
        code: "inter_div",
        name: "MPCA Inter-Divisional Tournament",
        family: "MPCA_InterDivisional",
        default_format: "Multi_Day",
        default_scope: "Inter_Divisional",
        icon: "trophy",
        one_liner: "State-level trophies played between MPCA Divisions (MY Memorial, Madhavrao Scindia, JN Bhaya).",
        input_hint: "Pools & hosts, days per match, knockout structure, prize incentives.",
        eligible_hosts: ["MPCA", "Division"],
    },
    {
        code: "inter_district",
        name: "Inter-District Tournament",
        family: "MPCA_InterDivisional",
        default_format: "Multi_Day",
        default_scope: "Inter_District",
        icon: "shield",
        one_liner: "Compulsory Division-level tournament between constituent Districts.",
        input_hint: "Per-day ceilings (INR 28k one-team, 39k both-teams), umpires, ground rent.",
        eligible_hosts: ["Division"],
    },
    {
        code: "inter_div_travel",
        name: "Inter-Divisional Participation (Travel Subsidy)",
        family: "MPCA_InterDivisional",
        default_format: "Multi_Day",
        default_scope: "Inter_Divisional",
        icon: "route",
        one_liner: "Travel subsidy claim when a Division plays away in an MPCA Inter-Divisional tournament.",
        input_hint: "III-tier AC rail fare, feeder legs from District HQ, Tatkal premium.",
        eligible_hosts: ["Division"],
    },
    {
        code: "pre_camp",
        name: "Pre-Tournament Camp (Divisional Team)",
        family: "MPCA_InterDivisional",
        default_format: "Multi_Day",
        default_scope: "Inter_Divisional",
        icon: "dumbbell",
        one_liner: "8-day camp ahead of an Inter-Divisional tournament (league or knockout stage).",
        input_hint: "Camp days ≤ 8, players 18-20, coach + trainer honoraria, medical actuals.",
        eligible_hosts: ["Division"],
    },
    {
        code: "reciprocal",
        name: "Reciprocal Matches Between Divisions",
        family: "MPCA_InterDivisional",
        default_format: "Multi_Day",
        default_scope: "Inter_Divisional",
        icon: "arrow-left-right",
        one_liner: "Bilateral 2-day matches between two Divisions in a specific age group.",
        input_hint: "Total camp+reciprocal days ≤ 8, host claims stay + food + officials.",
        eligible_hosts: ["Division"],
    },
    {
        code: "coaching_camp",
        name: "Periodical Coaching Camp (District Players)",
        family: "MPCA_InterDivisional",
        default_format: "Multi_Day",
        default_scope: "Inter_District",
        icon: "notebook-pen",
        one_liner: "Two-week coaching camp for district-level players run by a Division.",
        input_hint: "Camp days ~14, ₹15k misc cap, prior MPCA notification mandatory.",
        eligible_hosts: ["Division"],
    },
    {
        code: "vacation_camp",
        name: "Vacation Camp",
        family: "MPCA_InterDivisional",
        default_format: "Multi_Day",
        default_scope: "Inter_District",
        icon: "sun",
        one_liner: "Vacation-window camp (typically 2-3 weeks) with outstation + local players.",
        input_hint: "Free of charge to players — Secretary's undertaking required.",
        eligible_hosts: ["Division"],
    },
    {
        code: "inter_school",
        name: "Inter-School Tournament",
        family: "Invitational",
        default_format: "OneDay",
        default_scope: "Inter_District",
        icon: "graduation-cap",
        one_liner: "Boys/Girls knockout — up to 12 schools at Div HQ, 8 at a District.",
        input_hint: "25 ov (till SF), 50 ov (SF+F), ₹5k grant/day, entry fee ₹1.5k/team.",
        eligible_hosts: ["Division", "District"],
    },
    {
        code: "inter_club",
        name: "Inter-Club Tournament ('A' Grade)",
        family: "Invitational",
        default_format: "Multi_Day",
        default_scope: "Inter_District",
        icon: "flag",
        one_liner: "Two-day knockout among 10-12 'A' grade clubs of a Division.",
        input_hint: "Only two-day knockout reimbursed; outstation clubs get stay+food+travel.",
        eligible_hosts: ["Division"],
    },
    {
        code: "bcci_staging",
        name: "BCCI Domestic Tournament (Staging)",
        family: "BCCI",
        default_format: "FiveDay",
        default_scope: "Championship",
        icon: "shield-check",
        one_liner: "Hosting a BCCI tournament (Ranji, CK Nayudu, U-19 etc.) at an MPCA venue.",
        input_hint: "Host fee ₹1.75L/day multi-day, ₹3.5-4.5L limited-overs; cars, anti-doping room.",
        eligible_hosts: ["MPCA", "Division"],
    },
    {
        code: "away_participation",
        name: "BCCI Away Participation (MP Team)",
        family: "BCCI",
        default_format: "FiveDay",
        default_scope: "Championship",
        icon: "plane",
        one_liner: "MP team travelling to another State for a BCCI tournament.",
        input_hint: "Air/rail fare + hotel ₹3.4k/night + ₹500/day allowance + subsidy receivable.",
        eligible_hosts: ["MPCA"],
    },
];

export const getTypeByCode = (code) => TOURNAMENT_TYPE_CATALOG.find((t) => t.code === code) || null;
